name: Regression
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          browser : chrome

      - name: Cypress Test Report
        uses: actions/upload-artifact@v3
        with:
            name: MochaAwesome HTML Reports
            path: cypress/reports/html
